accounts/urls.py
from django.urls import path
from . import views

app_name='accounts'
urlpatterns = [
    path('signup',views.signup_view, name='signup'),
    path('login',views.login_view, name='login'),
    path('logout',views.logout_view, name='logout'),
]

articles/urls.py
from django.urls import path
from . import views
app_name = "articles"
urlpatterns = [
    path('',views.articles_list, name="list"),
    path('create',views.articles_create, name="create"),
    path('<slug>',views.detail, name= "detail"),
]

gaming_shop/urls.py
from django.contrib import admin
from django.urls import path , include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static
from articles.views import articles_list


urlpatterns = [
    path('admin/', admin.site.urls),
    path('about/',views.about),
    path('',articles_list),
    path('articles/' , include('articles.urls')),
    path('accounts/' , include('accounts.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

articles/models.py
from django.db import models
from django.contrib.auth.models import User

class Article(models.Model):
    title = models.CharField(max_length = 100)
    slug = models.SlugField(unique = True,allow_unicode = True)
    body = models.TextField()
    date = models.DateTimeField(auto_now_add = True)
    image = models.ImageField(default='default.jpg',blank=True)
    author = models.ForeignKey(User,default=None,on_delete=models.CASCADE)
    def __str__ (self):
        return self.title

    def pangah_ta_gelo_boro (self):
        return self.body[0:50] + ' ...'

articles/forms.py
from django import forms
from . import models

class ArticleCreate(forms.ModelForm):
    class Meta:
        model = models.Article
        fields =['title','body','image']

accounts/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth import login
from django.contrib.auth import logout


def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request,user)
            #login
            return redirect('articles:list')
    else:
        form = UserCreationForm()
    return render(request,'accounts/signup.html',{'form':form})


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get("next"))
            else:
                return redirect('articles:list')
    else:
        form = AuthenticationForm()
    return render(request,'accounts/login.html',{'form':form})
def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('articles:list')

articles/views.py
from django.shortcuts import render,HttpResponse,redirect
from . import models
from django.contrib.auth.decorators import login_required
from . import forms


def articles_list(request):
    articles = models.Article.objects.all().order_by('-date')
    collect = {'articles': articles}
    return render(request, 'articles/articleslist.html', collect)
def detail(request, slug):
    #return HttpResponse(slug)
    article = models.Article.objects.get(slug=slug)
    return render(request, 'articles/articles_detail.html',{'article':article})

@login_required(login_url = "/accounts/login")
def articles_create(request):
    if request.method == 'POST':
        form = forms.ArticleCreate(request.POST,request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.author = request.user
            form.save()
            return redirect('articles:list')
    else:
        form = forms.ArticleCreate()
    return render(request , 'articles/create.html',{'form':form})

gaming_shop/views.py
from django.shortcuts import render

def about(request):
    return render(request,'about.html')

def home(request):
    return render(request,'home.html')

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% block content %}
<h1>login</h1>
<form class="" action="{% url 'accounts:login' %}" method="post">
{{form}}
{% csrf_token %}
{% if request.GET.next %}
<input type="hidden" name="next" value="{{request.GET.next}}">
{% endif %}
<input type="Submit" value="login">
</form>
{%endblock%}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h1>sign up</h1>
 <form class="site-form" action="/accounts/signup" method="post">
{{form}}
{% csrf_token %}
<input type="submit" name="" value="signup">
 </form>
 <script src="{% static 'wellcome.js' %}"></script>
{%endblock%}

articles/templates/articles/articles_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="articles_detail">
  <div class="article">
    <img src="{{article.image.url}}" alt="">
    <h1>{{article.title}}</h1>
    <p>{{article.body}}</p>
    <p>{{article.date}}</p>
{% endblock %}

articles/templates/articles/articleslist.html
{% extends 'base.html' %}
 {% load static %}
{%block content%}

{%block title%}
wellcom to Article
{%endblock%}
    <h1>Article_list</h1>
    <div class="articles">
    {% for article in articles %}
    <div class="article">
    <h2><a href="{% url 'articles:detail' slug=article.slug %}">{{article.title}}</a></h2>
    <p>{{article.pangah_ta_gelo_boro}}</p>
    <p>{{article.date}}</p>
    <p class="author">add by {{article.author.username}}</p>
    </div>
    {% endfor %}
    </div>

{%endblock%}

articles/templates/articles/create.html
 {% extends 'base.html' %}
 {% load static %}
 {% block content %}
 <div class="create">
  <h1>Create Your Post</h1>
  <form class="site-form" action="{% url 'articles:create'%}" method="post" enctype="multipart/form-data">>
    {{form}}
    {% csrf_token %}
    <input type="submit" name="" value="create"/>
  </form>
 </div>
 {%endblock%}

templates/about.html
{%extends 'base.html'%}
{%block content%}

{%block title%}
wellcom to About
{%endblock%}
    <h6>welcom</h6>
    <p>خوب ما تازه و قوی شروع کردیم و قوی ادامه میدیم</p>
{%endblock%}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>
      {%block title%}
      Article
      {%endblock%}
    </title>
    <link rel='stylesheet' href="/static/styles.css">
  </head>
  <body>
    <header>
    <h2><a href="{% url 'articles:list' %}">LOGO</a></h2>
    <nav>
      <ul>
        {% if user.is_authenticated %}
        <li>
          <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
            {% csrf_token %}
            <button type="submit">LOGOUT</button>
          </form>
        </li>
        <li>
          <a class='highlight' href="{% url 'articles:create' %}"> CREATE NEW ARTICLES </a>
        </li>
        {% else %}
        <li>
          <a href="{% url 'accounts:login' %}">LOGIN</a>
        </li>
        <li>
          <a href="{% url 'accounts:signup' %}">SIGNUP</a>
        </li>
        {% endif %}
      </ul>
    </nav>
    </header>
    <div class="wrapper">
{%block content%}
{%endblock%}
  </div>
  </body>
</html>

templates/home.html
{%extends 'base.html'%}
{%block content%}

{%block title%}
wellcom to Home
{%endblock%}
    <h3>welcom</h3>
    <p>خوش اومدید به سایت خودتون ما خدمات خرید و فروش ویباکس و اکانت رو انجام میدیم</p>
{%endblock%}